<?php

return [
    'redx' => [
        'jwt_token' => 'eyJpdiI6InFpUW1TT3FUMGY3QmpJc2FKQWF2NGc9PSIsInZhbHVlIjoiTU9ZYmZwNUhUbFFVcnZQbGNhOXRDdz09IiwibWFjIjoiNjkzNTcxOTA0YTFkNmI4NzMyZjkxZmI5ZjU5YzQ1ZjhkZjZjYWQzOGQ1YmRlZjlhMTBjNmZjODJkMDg0ZTBkOSIsInRhZyI6IiJ9',
    ],
    'pathao' => [
        'mail' => 'eyJpdiI6ImQvVENEemJnZlEyRW9aZ1JRY1lXa0E9PSIsInZhbHVlIjoiLzBkSGkxSGtKMEN3Mm5NQzFEUnd6cWtEUUNQSUFGaTR0WWptTjk5ZXlXbz0iLCJtYWMiOiI5NWNiMmNkYTVmYzQzMmRmMmI3OTkyYWNmYzM0MDgxMDIzOTJiYzFjYjZiZWRkZjg2NDQwMTg0ZjFkMTlmY2Y2IiwidGFnIjoiIn0=',
        'password' => 'eyJpdiI6IlBkbkpMYmszMnRaWUNVOGFGbHVhSkE9PSIsInZhbHVlIjoieXUrYXdGeHpRMllub1FzK3JxdE5udz09IiwibWFjIjoiMTZlOWVkOGVlOTg0ODE3OGNiZjIxODMyOGI0N2ZmMDE5ZTEyMzQwM2U4ZWEyNDQ1ZDM3NTIxN2U1NjBlNGY4OSIsInRhZyI6IiJ9',
        'client_id' => 'eyJpdiI6IkFvZ3dUcGhrM3JDdFlZaGc2UE41bVE9PSIsInZhbHVlIjoicEZheU9jMzBDV1Z4dXk5RE00bUtCQT09IiwibWFjIjoiMjI5OTVhYmI2ZTQ2ZjAyNzk5NmYyMzY0NzJjMGRkYzA3ZTJiNWRlMmQxYWM3YzA5ZDI0MWQ4NDA0YWNlYzU1ZSIsInRhZyI6IiJ9',
        'client_secret' => 'eyJpdiI6Ik1GNnhVU1pKdXRBZlVBeHJWOW9lWXc9PSIsInZhbHVlIjoiZzIrY0pJSUZVQjdxNk90TUxyT2xaM2xKajRHTENvaVkvWFZsbVJ1RitpbDhpTTIrb2RISGhQZ3BuUXZhQ0ZwTyIsIm1hYyI6IjI2Y2QzNTFjZmE5MDllOWE4NmUxMjJhZjllMDE1Mzc3OTExMzI2ZmQ3NDM1MTM4ZWM5ZDgxODhmZjI1NmViYjgiLCJ0YWciOiIifQ==',
        'store_id' => 'eyJpdiI6IjN0QVVzL3F6TEtuNVR6S3ZZSG1iWGc9PSIsInZhbHVlIjoiUHQ1Zm1wbmljcTFTNmxSMWpmT0lMUT09IiwibWFjIjoiZDg0ZmNhOGMzMTNkOTIxODVkZDk5OGMyNzJmNTRkOWY4YTFhNDJlNjJjYWEyYzI0NWM2NmQ1ZmE5OTE2NjMzNCIsInRhZyI6IiJ9',
    ],
    'steadfast' => [
        'api_key' => 'eyJpdiI6Im9JTDh5eDlMbFFqMnNlL3dDcXNYcGc9PSIsInZhbHVlIjoibFdFSzc4ZEFQcDQ3YWJPd2ZnLzFnQT09IiwibWFjIjoiNWY5YjlhNmRjNzkzMmU0N2I0ZWU5MjhmNWNjZDk1ODZjZjI1M2RiNWU5ODVkNDc4OTQ2M2QyMWM5NjlhZWViMSIsInRhZyI6IiJ9',
        'api_secret' => 'eyJpdiI6InBYcE9TaENlbVZqeXpjOHpoY1phYnc9PSIsInZhbHVlIjoiNHRjSXE3dS80Q2hhaitMQWxIalBIZz09IiwibWFjIjoiMzkwNzMyM2Q0MzQ3NDdkN2UzMTUyNDQ4OWZkMzYyY2UzMTViZmM1Nzg4NzA5ZjYyMDVhOWZiNzIxYzdmMmQ4NCIsInRhZyI6IiJ9',
    ],
    'ecourier' => [
        'api_key' => 'eyJpdiI6ImFqdGtSVXBzTEdZK1dDdUtlTjdFckE9PSIsInZhbHVlIjoidm5Zd2FrVU43R3R5alhQSVpVVzE5QT09IiwibWFjIjoiOGFmZmNhNTA4MzYxN2JjN2FjODE5MWMwZTA0ZTExY2MzNWRkNTBkZmJiNDJjOWJhYjdmZDZjZGUwMDE0NzYzOSIsInRhZyI6IiJ9',
        'user_id' => 'eyJpdiI6Ijkzc3FvZk5LdWJCai9jZmM3TWV3RkE9PSIsInZhbHVlIjoiZFMxM25FVXRrSTRmVForVEJIUGd0dz09IiwibWFjIjoiY2U1NDY1MDViZWQ0NWRjZjkzYjc0OWIzNDhhNTYzMWQ0NTYzOTA1ODdjNmJmZmFiOTFlYjgxMmQ0NTU1NWE5NyIsInRhZyI6IiJ9',
        'api_secret' => 'eyJpdiI6IlU0U0VFRnlSU2JiTk5IR3VGclB5SHc9PSIsInZhbHVlIjoiWVNMVGdRbzMrVjN1UUswaTFLSUhsdz09IiwibWFjIjoiMTMzYWJiMTdlZmQ1MDU2NTAzM2NjM2M5ZWZiOTdhODNmNmFmN2E2NjVlZmI5Yjk3M2M1NGY1YmY1MTQ0MDk0YiIsInRhZyI6IiJ9',
    ],
];
